### ISSUE TITLE
Changes item information

### ISSUE THREAD

**Issue by Sakanas** [JEFF-Media-GbR/Spigot-Drop2Inventory#1]
when I put a gold bag of MOBHUNTING or some head of the plugin SLIMEFUN when I retire the head it loses the information, when I am full inventory it and collect some block it disappears, it joins items of the same floor with full inventory and adds with the item

**Comment by mfnalex** [comment]
Sorry I don‘t understand. You are using a third plugin that creates custom items, and those data is lost?
Is this only happening with skulls? I can add an option to disable the automatic collection for specific items if that is what you need.

**Comment by Sakanas** [comment]
also happens with plugin blocks like Enchantment table furnace and any other plugin item that is renamed.

**Comment by mfnalex** [comment]
This is because I am using the method block.getDrops(). When you have custom items, I have no way to predict what would be dropped. Do all items you are using have custom names? Please provide a screenshot of some of the items like they should be dropped (e.g. with lore and display name). Maybe I can create a workaround.

Unfortunately, if the plugins you mentioned handle the drops for their specific items, I can not just get the drop via Spigot API but I would have to add support for each plugin manually.

**Comment by mfnalex** [comment]
> when I put a gold bag of MOBHUNTING or some head of the plugin SLIMEFUN when I retire the head it loses the information, when I am full inventory it and collect some block it disappears, it joins items of the same floor with full inventory and adds with the item

The new version has an option to disable automatic drops for certain block types. Maybe this solves your problem :)
