### ISSUE TITLE
mcMMO hook seems to no longer work

### ISSUE THREAD

**Issue by gominecraft** [JEFF-Media-GbR/Spigot-Drop2Inventory#22]
mcMMO hook, in spite of being enabled, no klonger gives XP for trees being cut down unless you cut from top to bottom (negating the use of UT).

MC Version: 1.15.1
mcMMO Version: 2.1.112

**Comment by mfnalex** [comment]
I don't think that giving XP has ever worked since there is no reliable API method within mcMMO when I have last checked.

I might investigate this further at a later time, but right now my focus lies on ChestSort and my premium plugins. If you have any idea on how to have mcMMO recognize events from third party plugins, please let me know :)

**Comment by mfnalex** [comment]
this should have been fixed, please reopen if it still doesn't work
