### ISSUE TITLE
Spawner bug!

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#6]
I'm using an add-on called Mineable Spawners to get back with the digging of the silky spell, whereas the spawner gets lost when it breaks.

http://prntscr.com/mkybe0

please fix this.

**Comment by successed** [comment]
@mfnalex this problem here.

**Comment by mfnalex** [comment]
The problem is the following: a spawner will normally not drop, so the method .getDrops will return null.

I can not support other plugins directly, because of conflicting event priorities, but I can add a workaround: how about a list with disabled-blocks in the config? You can just add "mob_spawner" to that list, and Drop2Inventory will no longer manipulate any BlockBreakEvents regarding mob spawners. That will mean, however, that the spawner will drop normally and will not be automatically collected.

Would that be acceptable?

**Comment by successed** [comment]
Yes of course, and 1 more problem in config file

http://prntscr.com/mkyjy5

language not changed...

**Comment by mfnalex** [comment]
Ok perfect, I will add this.

And thanks for the language bug report, will also be fixed.

**Comment by mfnalex** [comment]
By the way, could you provide the translation as text so that I can include it for the next version? :)

**Comment by successed** [comment]
> Ok perfect, I will add this.
> 
> And thanks for the language bug report, will also be fixed.

And 1 more problem, 
When we break a mine with the magic of fortune, we give only 1 piece and when I close the plugin it gives 3 pieces.

**Comment by mfnalex** [comment]
Yeah I know, fortune has not been added yet, that is also on the todo list.

**Comment by successed** [comment]
##### turkish #####
message-disabled: "&bDrop2Inventory: &cKAPANDI"
message-enabled: "&bDrop2Inventory: &aAÇILDI"
message-when-breaking-block: "&bDrop2Inventory: &6Kırdığınız eşyaların otomatik olarak üzerinize gelmesini istiyorsanız &4/Drop2Inventory"
message-when-breaking-block2: "&bDrop2Inventory: &6Kırdığınız eşyaların otomatik olarak üzerinize gelmesini kapatmak için &4/Drop2Inventory"
And /ototopla is my aliases: ototopla

**Comment by successed** [comment]
also I suggest you add features to vip players.

**Comment by mfnalex** [comment]
Translation bug has been fixed and disabled blocks list has been added. Please create a new issue for the vip feature ideas you mentioned :)
