### ISSUE TITLE
Fortune bugs...

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#9]
http://prntscr.com/mlhizr

When the iron ore breaks it should give more than 1 piece.
other blocks show the same problem.

**Comment by successed** [comment]
http://prntscr.com/mlhu9b
2 different names of seeds.
1 : http://prntscr.com/mlhul4
2 : http://prntscr.com/mlhuoz

**Comment by mfnalex** [comment]
what version are you using? fortune has been added in the latest update

**Comment by successed** [comment]
i have latest 3.6

**Comment by mfnalex** [comment]
The behaviour is correct. Ores that drop themselves will not be affected by fortune, because it could be used to duplicate it. Try it with vanilla, it will result in the same behaviour. Only coal, emerald, diamonds, lapis lazuli and redstone are multiplied using fortune. Iron and Gold will still drop 1 ore every time.

**Comment by mfnalex** [comment]
See here: https://minecraft.fandom.com/wiki/Enchantments#Fortune

**Comment by successed** [comment]
Sorry it's my fault.

**Comment by mfnalex** [comment]
No problem, I was also confused until I realized it
